title: "Tryaksh Gupta"
email: "tryaksh@umich.edu"
description: "Portfolio - Design, Computational Modeling & Simulation"
github_username: "tryaksh"
minimal_mistakes_skin: "default"
search: true

# Build / Theme
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
include:
  - _pages

# Plugins (lean)
plugins:
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name   : "Tryaksh Gupta"
  avatar : "/assets/images/bio-photo.jpg"   # remove or update if not present
  bio    : "My work lives where product thinking meets design, modeling, and simulation."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/tryakshgupta"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/tryakshgupta"
    # - label: "Instagram"   # optional
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://www.instagram.com/tryaksh.gupta"

# Defaults (pages only)
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
