title: "Tryaksh Gupta"
email: "tryaksh@umich.edu"
description: "Product · Design · Modeling · Simulation"
github_username: "tryaksh"
minimal_mistakes_skin: "default"
search: true
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
include: [_pages]
plugins: []  # keep your current plugins if you have them

author:
  name   : "Tryaksh Gupta"
  avatar : "/assets/images/bio-photo.jpg"   # already in your repo
  bio    : "PM/Engineer building simulation & robotics products at Spatial (Dassault Systèmes)."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/tryakshgupta"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/tryaksh"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:tryaksh@umich.edu"
